### ISSUE TITLE
Outbound emails

### ISSUE THREAD

**Issue by david03g** [lichess-org/lila-docker#53]
I was looking to have real outbound emails for registration. I'm not sure how to configure the docker image to do this.

**Comment by fitztrev** [comment]
lila has a `base.conf` file with the possible config values, then this repo loads the [lila.conf](https://github.com/lichess-org/lila-docker/blob/main/conf/lila.conf) file into the container as `application.conf` to override specific values.

**Comment by david03g** [comment]
@fitztrev I tried configuring it as follows:

mailer.primary.mock = false
mailer.primary.tls = true
mailer.primary.host = "smtp.mailgun.org"
mailer.primary.port = 25
mailer.primary.sender = "******.com <support"******.com>"
mailer.primary.user = "postmaster@******.com"
mailer.primary.password = "******"
security.email_confirm.enabled = true

There was no field for user and password, so I added them after seeing them in Mailer class in lila codebase. 

This did not work. 

Am I close or completely wrong?

**Comment by fitztrev** [comment]
Seems right. Assuming you've restarted lila and nothing in the error logs? Maybe also spin up a test smtp server and see if you see connection attempts to it.

**Comment by david03g** [comment]
@fitztrev My SMPT credentials are valid and there were no errors in the logs. However, I was using gitpod. Could that have something to do with it or would it be same as local machine or instance?
