### ISSUE TITLE
option to download fide database from network on startup

### ISSUE THREAD

**Issue by SergioGlorias** [lichess-org/lila-docker#76]
it would help when we are working with broadcasts

**Comment by fitztrev** [comment]
Can you clarify? Do you mean the mongodb data or data from database.lichess.org?

And then how would you envision it being used?

**Comment by SergioGlorias** [comment]
I forgot to mention that I was talking about FIDE

**Comment by fitztrev** [comment]
Ok, thanks. Not sure how this could be automated during the setup. For now, I think just going to `/dev/cli` and running the command is reasonable. It also makes HTTP requests to a 3rd party so I think keeping the low barrier is a way to limit them.
