### ISSUE TITLE
Add subcommand to pick up where the setup left off

### ISSUE THREAD

**Issue by ProjectHSI** [lichess-org/lila-docker#80]
Occasionally, the setup appears to crash in various places.

I think it'd be good to have a command which restarts from the step where it failed at (restarting the step as well).

**Comment by fitztrev** [comment]
Will look into. Could you provide an example of when it crashed and how you were able to tell?

**Comment by ProjectHSI** [comment]
This happened on my fork of `lila-docker` for reasons not related to this issue, but the issue happened on the original repository as well.
<img width="1263" alt="Screenshot 2024-04-25 152819" src="https://github.com/lichess-org/lila-docker/assets/57279339/42f6b5b8-6fe5-428f-98fc-4025d9e11a27">

**Comment by ProjectHSI** [comment]
this might actually be a bug with bbppairing. i'll look into it

**Comment by ProjectHSI** [comment]
no issues tab on bbppairing. atleast lichess' version

**Comment by ProjectHSI** [comment]
wait no it's this repo

**Comment by ProjectHSI** [comment]
it's been mostly failing on just the first line, the FROM directive.
https://github.com/lichess-org/lila-docker/blob/main/docker/bbpPairings.Dockerfile

**Comment by Carbrex** [comment]
> This happened on my fork of `lila-docker` for reasons not related to this issue, but the issue happened on the original repository as well. <img alt="Screenshot 2024-04-25 152819" width="1263" src="https://private-user-images.githubusercontent.com/57279339/325483996-42f6b5b8-6fe5-428f-98fc-4025d9e11a27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjAyMTQsIm5iZiI6MTcxNDcxOTkxNCwicGF0aCI6Ii81NzI3OTMzOS8zMjU0ODM5OTYtNDJmNmI1YjgtNmZlNS00MjhmLTk4ZmMtNDAyNWQ5ZTExYTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDA3MDUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5YjNiOTFmYTMzMjdkNTliNmQ3NjJjMTQ5ZDQxOGJhN2M4ODQ0NTc1OTVhYzc5NThkYjhkOWY0OTRkYjhjNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EXTReoFtozyxyXVHP2uWXFtZjdWkF9-zFJc2C60KOeI">

I am not on mac but I can't reproduce it on my machine.

**Comment by benediktwerner** [comment]
@ProjectHSI This is an issue with your Docker setup or configuration.

**Comment by ProjectHSI** [comment]
> @ProjectHSI This is an issue with your Docker setup or configuration.

Strange... what's even stranger is that everything else always works, every time. Excluding mistakes of my own of course.

**Comment by Carbrex** [comment]
@ProjectHSI https://serverfault.com/questions/1130018/how-to-fix-error-internal-load-metadata-for-docker-io-error-while-using-dock

**Comment by ProjectHSI** [comment]
not going to rebuild lila for a long time (atleast i don't think) but i will close this issue as not completed because of this.
