### ISSUE TITLE
[Question] How to configure analysis depth ?

### ISSUE THREAD

**Issue by KaKi87** [lichess-org/lila-docker#81]
Thanks

**Comment by KaKi87** [comment]
> Do you mean for fishnet?

Yes, I think.

The truth is, I don't really know how Lichess or Stockfish works, not even chess in general, but a friend mentioned they're frustrated with the computation depth limits of the main Lichess instance, and considered paying for a premium provider like Chessify, but since I already have a server that's quite powerful, I'd like to try hosting one myself with higher parameters for them to use for free.

Thanks

**Comment by fitztrev** [comment]
The Analysis page allows you connect to an External Engine that you can have running on your own machine https://lichess.org/api#tag/External-engine

You could either write your own client to connect to those API endpoints or try https://github.com/fitztrev/lichess-tauri

**Comment by KaKi87** [comment]
So I don't actually have to host a Lichess instance, but only an engine, so that they could use lichess-tauri to connect to it ?

What do I have to install on my server then ?

Thanks

**Comment by fitztrev** [comment]
No server is required. The app and engine would be run locally.

**Comment by KaKi87** [comment]
Unfortunately, their personal computer isn't powerful enough for that, they already tried. Thanks
