### ISSUE TITLE
docker start getting killed automatically on mac

### ISSUE THREAD

**Issue by prolificcoder** [lichess-org/lila-docker#84]
No idea about scala and how it runs but I installed docker on my mac and cloned this repo
When I run this command
` lila-docker git:(main) ./lila-docker start` 
it takes a while and seems to be going to good but after a bit I see this error

```
lila-1  | [info] done compiling
lila-1  | [info] compiling 7 Scala sources to /lila/modules/appeal/target/scala-3.4.1/classes ...
lila-1  | [info] done compiling
lila-1  | [info] compiling 6 Scala sources to /lila/modules/playban/target/scala-3.4.1/classes ...
lila-1  | Killed
lila-1 exited with code 0
```

<img width="721" alt="image" src="https://github.com/lichess-org/lila-docker/assets/149176/b4a9fd1e-9f9f-4abf-b719-ca0ea7b8c53a">
I have a decent machine
<img width="289" alt="image" src="https://github.com/lichess-org/lila-docker/assets/149176/6112d421-931c-4b15-a1da-e07aef7068f9">

Should I allocate more memory to docker or something on those lines?

**Comment by benediktwerner** [comment]
Yes, running out of memory seems like a good guess. How much did you allocate to it? Not sure what the minimum limit is but something like 6-8 GB should probably be enough.

**Comment by fitztrev** [comment]
Closing for now. If you're still having issues, feel free to reply with more info.

**Comment by bastianpedersen** [comment]
I am facing the exact same issue.
